#!/bin/bash

cd ~/cimaBot
gnome-terminal --tab --title="cimaBot" --command="python3 cimaBot.py" && pid=$!

while true;
do

    if pgrep -f "python3 cimaBot.py" &>/dev/null; then
        echo "El bot está en funcionamiento."
    else
        echo "El bot se ha caído, reiniciando..."
        kill -9 pid
        cd ~/cimaBot
        gnome-terminal --tab --title="cimaBot" --command="python3 cimaBot.py"
        echo "Bot en marcha de nuevo."
    fi
    sleep 300
done
